services:
  - type: web
    name: laravel-app
    env: docker
    repo: https://github.com/AlexSuvak94/cars_management
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel_db
          property: password